"""
Playwright Script Generator — converts TestCase objects into executable
Playwright-Python test scripts using Jinja2 templates.
"""
from __future__ import annotations

import logging
import textwrap
from pathlib import Path

from jinja2 import Environment, BaseLoader

from src.config import settings
from src.models import TestCase, TestSuite, TestType

logger = logging.getLogger(__name__)

# ── Jinja2 template for generated test files ─────────────────────────────────

UI_TEST_TEMPLATE = """\
\"\"\"
Auto-generated Playwright UI test — {{ suite_name }}
Module: {{ module }}
Generated by CRM AI Test Agent
\"\"\"
import re
import pytest
import allure
from playwright.sync_api import Page, expect


BASE_URL = "{{ base_url }}"

{% for tc in test_cases %}
@allure.severity(allure.severity_level.{{ tc.severity | upper }})
@allure.feature("{{ module | capitalize }}")
@allure.story("{{ tc.title }}")
@pytest.mark.{{ module }}
@pytest.mark.ui
class Test{{ tc.class_name }}:
    \"\"\"{{ tc.description }}\"\"\"
{% for pre in tc.preconditions %}
    # Precondition: {{ pre }}
{% endfor %}

    def test_{{ tc.method_name }}(self, page: Page):
        with allure.step("Navigate to {{ module }} page"):
            page.goto(f"{BASE_URL}{{ ui_route }}")
            page.wait_for_load_state("networkidle")

{% for step in tc.steps %}
        with allure.step("{{ step.action | replace('"', '\\\\"') }}"):
{% if 'click' in step.action.lower() %}
            page.locator("{{ step.target }}").click()
{% elif 'type' in step.action.lower() or 'fill' in step.action.lower() or 'enter' in step.action.lower() %}
            page.locator("{{ step.target }}").fill("{{ step.value }}")
{% elif 'assert' in step.action.lower() or 'verify' in step.action.lower() or 'check' in step.action.lower() %}
            expect(page.locator("{{ step.target }}")).to_be_visible()
{% elif 'navigate' in step.action.lower() or 'go to' in step.action.lower() %}
            page.goto(f"{BASE_URL}{{ step.target }}")
            page.wait_for_load_state("networkidle")
{% elif 'wait' in step.action.lower() %}
            page.wait_for_timeout(1000)
{% else %}
            # {{ step.action }}: {{ step.target }} → {{ step.value }}
            pass
{% endif %}
{% endfor %}

        with allure.step("Verify expected result"):
            # Expected: {{ tc.expected_result }}
            pass

{% endfor %}
"""

API_TEST_TEMPLATE = """\
\"\"\"
Auto-generated API test — {{ suite_name }}
Module: {{ module }}
Generated by CRM AI Test Agent
\"\"\"
import pytest
import allure
import requests


API_BASE = "{{ api_base }}"
AUTH_URL = "{{ auth_url }}"

@pytest.fixture(scope="module")
def auth_token():
    resp = requests.post(
        f"{AUTH_URL}/api/v1/auth/login",
        json={
            "email": "{{ admin_email }}",
            "password": "{{ admin_password }}",
            "tenantId": "{{ tenant_id }}",
        },
    )
    if resp.status_code == 200:
        data = resp.json()
        return data.get("token") or data.get("accessToken") or ""
    return ""


def _headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


{% for tc in test_cases %}
@allure.severity(allure.severity_level.{{ tc.severity | upper }})
@allure.feature("{{ module | capitalize }}")
@allure.story("{{ tc.title }}")
@pytest.mark.{{ module }}
@pytest.mark.api
class Test{{ tc.class_name }}:
    \"\"\"{{ tc.description }}\"\"\"

    def test_{{ tc.method_name }}(self, auth_token):
{% for step in tc.steps %}
        with allure.step("{{ step.action | replace('"', '\\\\"') }}"):
{% if 'POST' in step.action.upper() %}
            resp = requests.post(
                f"{API_BASE}{{ step.target }}",
                json={{ step.value or '{}' }},
                headers=_headers(auth_token),
            )
{% elif 'PUT' in step.action.upper() %}
            resp = requests.put(
                f"{API_BASE}{{ step.target }}",
                json={{ step.value or '{}' }},
                headers=_headers(auth_token),
            )
{% elif 'DELETE' in step.action.upper() %}
            resp = requests.delete(
                f"{API_BASE}{{ step.target }}",
                headers=_headers(auth_token),
            )
{% elif 'GET' in step.action.upper() %}
            resp = requests.get(
                f"{API_BASE}{{ step.target }}",
                headers=_headers(auth_token),
            )
{% else %}
            # {{ step.action }}
            pass
{% endif %}
{% endfor %}

        with allure.step("Verify expected result"):
            # Expected: {{ tc.expected_result }}
            pass

{% endfor %}
"""


# ── Helper to make safe Python identifiers ───────────────────────────────────

def _to_class_name(title: str) -> str:
    """'Create lead with valid data' → 'CreateLeadWithValidData'"""
    import re
    words = re.sub(r"[^a-zA-Z0-9 ]", "", title).split()
    return "".join(w.capitalize() for w in words)[:60]


def _to_method_name(title: str) -> str:
    import re
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", title).strip("_").lower()
    return slug[:80]


# ── Generator class ──────────────────────────────────────────────────────────

class PlaywrightScriptGenerator:
    """Renders TestSuite → executable .py test files."""

    def __init__(self):
        self.env = Environment(loader=BaseLoader(), autoescape=False)
        self.ui_tmpl = self.env.from_string(UI_TEST_TEMPLATE)
        self.api_tmpl = self.env.from_string(API_TEST_TEMPLATE)

    # ── public API ───────────────────────────────────────────────────

    def generate_scripts(self, suite: TestSuite, output_dir: Path | None = None) -> list[Path]:
        """
        Generate test script files from a test suite.
        Returns list of file paths written.
        """
        output_dir = output_dir or settings.generated_tests_dir
        output_dir.mkdir(parents=True, exist_ok=True)

        ui_cases = [tc for tc in suite.test_cases if tc.test_type in (TestType.UI, TestType.E2E, TestType.SMOKE)]
        api_cases = [tc for tc in suite.test_cases if tc.test_type in (TestType.API, TestType.REGRESSION)]
        # If a test has no type preference, default to API
        unclassified = [tc for tc in suite.test_cases if tc not in ui_cases and tc not in api_cases]
        api_cases.extend(unclassified)

        written: list[Path] = []

        if ui_cases:
            path = self._write_ui_tests(suite, ui_cases, output_dir)
            written.append(path)

        if api_cases:
            path = self._write_api_tests(suite, api_cases, output_dir)
            written.append(path)

        logger.info("Generated %d script files in %s", len(written), output_dir)
        return written

    # ── internals ────────────────────────────────────────────────────

    def _enrich_cases(self, cases: list[TestCase]) -> list[dict]:
        enriched = []
        for tc in cases:
            enriched.append({
                "title": tc.title,
                "description": tc.description,
                "severity": tc.severity.value.upper(),
                "preconditions": tc.preconditions,
                "expected_result": tc.expected_result,
                "class_name": _to_class_name(tc.title),
                "method_name": _to_method_name(tc.title),
                "steps": [
                    {
                        "action": s.action,
                        "target": s.target,
                        "value": s.value,
                        "expected": s.expected,
                    }
                    for s in tc.steps
                ],
            })
        return enriched

    def _write_ui_tests(self, suite: TestSuite, cases: list[TestCase], output_dir: Path) -> Path:
        from src.crm_modules import get_module
        try:
            mod = get_module(suite.module)
            ui_route = mod.ui_route
        except KeyError:
            ui_route = f"/{suite.module}"

        rendered = self.ui_tmpl.render(
            suite_name=suite.name,
            module=suite.module,
            base_url=settings.crm_base_url,
            ui_route=ui_route,
            test_cases=self._enrich_cases(cases),
        )
        path = output_dir / f"test_{suite.module}_ui.py"
        path.write_text(rendered, encoding="utf-8")
        logger.info("Wrote UI test: %s  (%d cases)", path, len(cases))
        return path

    def _write_api_tests(self, suite: TestSuite, cases: list[TestCase], output_dir: Path) -> Path:
        rendered = self.api_tmpl.render(
            suite_name=suite.name,
            module=suite.module,
            api_base=settings.crm_api_base,
            auth_url=settings.auth_service_url,
            admin_email=settings.test_admin_email,
            admin_password=settings.test_admin_password,
            tenant_id=settings.test_tenant_id,
            test_cases=self._enrich_cases(cases),
        )
        path = output_dir / f"test_{suite.module}_api.py"
        path.write_text(rendered, encoding="utf-8")
        logger.info("Wrote API test: %s  (%d cases)", path, len(cases))
        return path
